### PR TITLE
Make TF Go library go-gettable, generate protobuf code

### PR DESCRIPTION
**Pull request by janhartman**
In order to make the TF Go library go-gettable, two things have to be done:
- Generate Go code from protobufs - [commit  f4c193e](https://github.com/Zemanta/tensorflow/commit/f4c193e51274cf9be822dc4dc05c20aa8f5ef350). This was done by following [this guide in the TF build repo](https://github.com/tensorflow/build/tree/master/golang_install_guide).
- Switch all import paths from `tensorflow/tensorflow` to `Zemanta/tensorflow` - [commit a03ab71](https://github.com/Zemanta/tensorflow/commit/a03ab710373c7568d49e2dd730cd1d22c648f6dc)

There's a lot of changes, but mostly it's just code generation. I've confirmed that this branch can now be used when go-getting the library.

### CODE REVIEW

**Review by pr3mar — APPROVED** [review]
I'll trust you with this one :D

What's the process of upgrading the repo to the latest TF version?

**Comment by pr3mar** [comment]
Also, how do we run the tests to make sure everything is ok?

**Review by PrimozBelej — APPROVED** [review]

**Comment by janhartman** [comment]
@pr3mar I ran the tests locally as described in the linked build guide. I don't think it's worth the effort to set up CI tests here since we'll see if anything is broken in our code anyway.

**Review by davorink — APPROVED** [review]
🚒 🔥 🧑‍🚒

**Pull request merged**
